### ISSUE TITLE
Srt listener thread blocks forever if the connection was denied. 

### ISSUE THREAD

**Issue by Lighty0410** [sportsball-ai/av-rs#132]
Hey everyone! I've been using the srt bindings from this crate a lot lately and they are amazing! However, there's one issue with the srt listener. 
Consider this example: 
<details> 

```
use std::thread;
use std::time::Duration;

use srt::{
    ConnectOptions, Listener, ListenerCallback, ListenerCallbackAction, ListenerOption, Stream,
};

struct SomeCallBack;

impl ListenerCallback for SomeCallBack {
    fn callback(&self, _: Option<&str>) -> ListenerCallbackAction {
        ListenerCallbackAction::Deny
    }
}

fn main() {
    thread::spawn(|| {
        let listener = Listener::bind_with_options(
            "127.0.0.1:1236",
            [ListenerOption::TooLatePacketDrop(true)],
        )
        .unwrap()
        .with_callback(SomeCallBack)
        .unwrap();

        loop {
            if let Err(e) = listener.accept() {
                println!("server thread error: {}", e);
            }
        }
    });

    if let Err(e) = Stream::connect(
        "127.0.0.1:1236",
        &ConnectOptions {
            too_late_packet_drop: Some(true),
            ..Default::default()
        },
    ) {
        println!("client thread error: {}", e);
    };

    thread::sleep(Duration::from_secs(2)) // required for the listener being able to catch up with the main thread. 
}
```
</details> 

As soon as the client gets rejected the listener thread gets blocked until forever. And the only option to exit from the application is to abort it (SIGABRT), exiting with SIGEXIT doesn't help (probably because `process:exit()` calls `sys:cleanup()` but it's just an assumption). What's interesting i still can accept a new connection. However i cannot get to  the point after the `.accept()` call. Is there a fix for that? 
upd: the lock occurs [here](https://github.com/sportsball-ai/av-rs/blob/main/srt/src/lib.rs#L405) 
I'll be happy to provide any further testing/information if needed. Thanks in advance!

**Comment by ccbrown** [comment]
This is working as intended - the `srt_accept` only returns when connections are accepted. But I can see why this might be a problem as there's no nice way to gracefully shut down the listener until a new connection is made. [std](https://doc.rust-lang.org/std/index.html)::[net](https://doc.rust-lang.org/std/net/index.html)::[TcpListener](https://doc.rust-lang.org/std/net/struct.TcpListener.html#) has a [similar problem](https://stackoverflow.com/questions/29541821/how-to-break-from-the-blocking-tcplisteneraccept-call) - there's no way to exit its accept loop in between connections unless you set the listener to non-blocking.

At the moment there are two options:

* When you want to shut down the listener, create a connection to it so that `accept` returns.
* Use the async API (which is the one we use in production). With the async API, you can just drop the `accept` future at any time.

**Comment by Lighty0410** [comment]
> This is "working as intended" - the underlying `srt_accept` call only returns when connections are accepted (but doesn't return when connections are denied). But I can see why this might be a problem as there's no nice way to gracefully shut down the listener until a new connection is made. [std](https://doc.rust-lang.org/std/index.html)::[net](https://doc.rust-lang.org/std/net/index.html)::[TcpListener](https://doc.rust-lang.org/std/net/struct.TcpListener.html#) has a [similar problem](https://stackoverflow.com/questions/29541821/how-to-break-from-the-blocking-tcplisteneraccept-call) - there's no way to exit its accept loop in between connections unless you set the listener to non-blocking.
> 
> At the moment there are two options:
> 
> * When you want to shut down the listener, create a connection to it so that `accept` returns. (Hacky, I know.)
> * Use the async API (which is the one we use in production). With the async API, you can just drop the `accept` future at any time.

Thanks a lot for the info! Closing the issue.
